name: CI/CD to EKS using Helm

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EKS via Helm
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Configure kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_FILE }}" | base64 --decode > ~/.kube/config

    - name: Add Helm repo
      run: |
        helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
        helm repo update

    - name: Deploy with Helm
      run: |
        helm upgrade --install otel-demo open-telemetry/opentelemetry-demo \
          --namespace otel-helm --create-namespace || helm rollback otel-demo

    - name: Verify Deployment
      run: kubectl get all -n otel-helm
