name: CI/CD to EKS using Helm

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EKS via Helm
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Generate kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --region us-east-2 \
          --name otel-demo-cluster


    - name: Add Helm repo
      run: |
        helm repo add open-telemetry https://open-telemetry.github.io/opentelemetry-helm-charts
        helm repo update

    - name: Deploy with Helm
      run: |
        helm upgrade --install otel-demo open-telemetry/opentelemetry-demo \
  --namespace otel-helm --create-namespace \
  --set elasticsearch.enabled=false \
  --set jaeger.enabled=false \
  --set tempo.enabled=false \
  --set loki.enabled=false \
  --set grafana.enabled=false || helm rollback otel-demo


    - name: Verify Deployment
      run: kubectl get all -n otel-helm
